; Gogs Custom Config
;   - More info at https://github.com/gogs/gogs/blob/main/conf/app.ini

BRAND_NAME = ${BRAND_NAME}
RUN_USER   = git
RUN_MODE   = prod

[database]
TYPE     = postgres
HOST     = ${GOGS_DATABASE_HOST}
NAME     = ${GOGS_DATABASE_NAME}
USER     = ${GOGS_DATABASE_USER}
PASSWORD = ${GOGS_DATABASE_PASSWORD}
SCHEMA   = public
SSL_MODE = disable
PATH     = /app/gogs/data/gogs.db

[repository]
ROOT           = /data/git/gogs-repositories
DEFAULT_BRANCH = main

[server]
EXTERNAL_URL     = ${APP_URL}
DOMAIN           = ${APP_DOMAIN}
HTTP_PORT        = 3000
START_SSH_SERVER = true
DISABLE_SSH      = false
SSH_PORT         = 22
SSH_LISTEN_PORT  = ${SSH_PORT}
OFFLINE_MODE     = false
; The landing page URL for anonymous users, the value should not include
; subpath that is handled by the reverse proxy.
LANDING_URL = /

[email]
ENABLED = false

[auth]
REQUIRE_EMAIL_CONFIRMATION  = false
DISABLE_REGISTRATION        = true
ENABLE_REGISTRATION_CAPTCHA = false
REQUIRE_SIGNIN_VIEW         = false

[service]
DISABLE_REGISTRATION = true

[user]
ENABLE_EMAIL_NOTIFICATION = false

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = false

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = /app/gogs/log

[security]
INSTALL_LOCK = true
SECRET_KEY   = ${GOGS_SECURITY_SECRET_KEY}

[admin]
DISABLE_REGULAR_ORG_CREATION = true

[other]
SHOW_FOOTER_TEMPLATE_LOAD_TIME = false

[ui]
EXPLORE_PAGING_NUM = 25
ISSUE_PAGING_NUM = 25
FEED_MAX_COMMIT_NUM = 5

[ui.user]
REPO_PAGING_NUM = 15
NEWS_FEED_PAGING_NUM = 20
COMMITS_PAGING_NUM = 30
