; Gogs Local Config
;   - More info at https://github.com/gogs/gogs/blob/main/conf/app.ini
;   - Copy to 'app.ini' in this same directory and edit that file instead of this file

BRAND_NAME = Git
RUN_USER   = git
RUN_MODE   = prod

[database]
TYPE     = postgres
; Must match the value of GOGS_DATABASE_HOST from '.git.env'
HOST     =
; Must match the value of GOGS_DATABASE_NAME from '.git.env'
NAME     =
; Must match the value of GOGS_DATABASE_USER from '.git.env'
USER     =
; Must match the value of GOGS_DATABASE_PASSWORD from '.git.env'
PASSWORD =
SCHEMA   = public
PATH     = /app/gogs/data/gogs.db

[repository]
ROOT           = /data/git/gogs-repositories
DEFAULT_BRANCH = main

[server]
EXTERNAL_URL     = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/
DOMAIN           = localhost
HTTP_PORT        = 3000
START_SSH_SERVER = true
DISABLE_SSH      = false
SSH_PORT         = 22
; Must match the value of SSH_PORT from '.git.env'
SSH_LISTEN_PORT  =
OFFLINE_MODE     = false
; The URL path to show visitors when they visit '/' and aren't logged in
LANDING_URL      = /bcm
SSH_ROOT_PATH    = /data/ssh

[email]
ENABLED = false

[auth]
DISABLE_REGISTRATION        = true

[user]
ENABLE_EMAIL_NOTIFICATION = false

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = false

[session]
PROVIDER = file

[log]
MODE      = console, file
LEVEL     = Warn
ROOT_PATH = /app/gogs/log

[security]
INSTALL_LOCK = true
; Must match the value of GOGS_SECURITY_SECRET_KEY from '.git.env'
SECRET_KEY   =

[admin]
DISABLE_REGULAR_ORG_CREATION = true

[other]
SHOW_FOOTER_BRANDING            = false
SHOW_FOOTER_TEMPLATE_LOAD_TIME  = false

[ui]
EXPLORE_PAGING_NUM = 25
ISSUE_PAGING_NUM = 25
FEED_MAX_COMMIT_NUM = 5

[ui.user]
REPO_PAGING_NUM = 15
NEWS_FEED_PAGING_NUM = 20
COMMITS_PAGING_NUM = 30
