version: 2
updates:
  - package-ecosystem: "deno"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    assignees:
      - "bcm-works"
    groups:
      deps-deno:
        patterns:
          - "*"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    target-branch: "main"
    pull-request-branch-name:
      separator: "-"
      prefix: "fix-deps-deno-"
      branch-name-case: "lowercase"
