#!/usr/bin/env bash
#MISE description="Create a new Pull Request for the current branch"

current_branch="$(git rev-parse --abbrev-ref HEAD)"

target_branch="develop"

gh pr create \
  --title "$current_branch" \
  --body-file ".github/pull_request_template.md" \
  --assignee "@me" \
  --head "$current_branch" \
  --base "$target_branch" \
  --draft
