#!/usr/bin/env bash
#MISE description="Update third-party dependencies"
#MISE alias="deps"

mise run msg-info "Updating Deno dependencies"

deno task update

mise run msg-info "Updating NPM dependencies for 'infra'"

cd infra
npm update

mise run msg-warn "Dependencies updated, testing required"
