#!/usr/bin/env bash
#MISE description="Generates a changelog file for a release"
#USAGE arg "<output_file>" help="Path to output text file"

# Configure output format
GIT_LOG_FORMAT="- %s"

# Fetch all tags
git fetch --tags --force

# Get the most recent release tag name
PREV_GIT_TAG=$(git tag -l "release-*" --sort=-creatordate | head -n 1)

# Account for not having a previous release tag
if [ -z "$PREV_GIT_TAG" ]; then
  echo "No previous tag found"
  echo "" > "${usage_output_file}"
  exit 0
fi

# Generate the commit list between previous tag and current ref
git log "$PREV_GIT_TAG..HEAD" --oneline --no-merges --format="$GIT_LOG_FORMAT" > "${usage_output_file}"

# If no commits found, set a default
if [ ! -s "${usage_output_file}" ]; then
  echo "" > "${usage_output_file}"
fi
