#!/usr/bin/env bash
#MISE description="Initial setup of a local environment"

if command -v mise > /dev/null 2>&1 && [ -f "$HOME/.local/bin/mise" ] ; then
  mise run msg 'Activating Mise to apply config and aliases'
	eval "$($HOME/.local/bin/mise activate bash)"
fi

if command -v brew > /dev/null 2>&1; then
  mise run msg 'Found Homebrew' -t 'success'
else
  mise run msg 'Please install Homebrew manually - https://brew.sh/' -t 'error'
  exit 1
fi

if command -v docker > /dev/null 2>&1; then
  mise run msg 'Found Docker' -t 'success'
else
  mise run msg 'Please install Docker manually - https://www.docker.com/products/docker-desktop/' -t 'error'
  exit 1
fi

if command -v deno > /dev/null 2>&1; then
  mise run msg 'Found Deno' -t 'success'
else
  mise run msg 'Installing Deno'
  curl -fsSL https://deno.land/install.sh | sh
fi

mise run msg 'Installing GitHub CLI'
brew install gh > /dev/null 2>&1

mise run msg 'Installing the actionlint extension for GitHub CLI'
gh extension install cschleiden/gh-actionlint > /dev/null 2>&1

mise run msg 'Installing markdownlint'
brew install markdownlint-cli > /dev/null 2>&1

mise run msg 'Setup completed' -t 'success'

mise run msg 'To install optional AI Code Generation tools, see https://github.com/brendanmurty/dotfiles/blob/main/ai/ai-install.sh' -t 'warn'
