name: bcm-git

networks:
  bcm-git-network:
    name: bcm-git-network
    external: false

services:

  bcm-git-server:
    container_name: bcm-git-server
    image: codeberg.org/forgejo/forgejo:15-rootless
    user: "${USER_UID}:${USER_GID}"
    restart: no
    ports:
      - "${PORT_WEB}:3000"
      - "${PORT_SSH}:2222"
    networks:
      - bcm-git-network
    environment:
      USER_UID: "${USER_UID}"
      USER_GID: "${USER_GID}"
      FORGEJO____APP_NAME: "${APP_NAME}"
      FORGEJO____APP_SLOGAN: "${APP_SLOGAN}"
      FORGEJO____APP_DISPLAY_NAME_FORMAT: "${APP_DISPLAY_NAME_FORMAT}"
      FORGEJO__server__ROOT_URL: "${ROOT_URL}"
      FORGEJO__ui__SHOW_USER_EMAIL: "false"
      FORGEJO__ui__THEMES: "${APP_THEME_LIST}"
      FORGEJO__ui__DEFAULT_THEME: "${APP_THEME_DEFAULT}"
      FORGEJO__database__DB_TYPE: "sqlite3"
      FORGEJO__database__PATH: "data/${APP_NAME}.${APP_ENV}.live.db"
    volumes:
      - "bcm-git-volume-app:/var/lib/gitea"
      - "bcm-git-volume-data:/var/lib/gitea/data"
      - "bcm-git-volume-git:/var/lib/gitea/git"
      - "bcm-git-volume-custom:/var/lib/gitea/custom"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

volumes:
  bcm-git-volume-app:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${STORAGE_DIR_APP}"
  bcm-git-volume-custom:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${STORAGE_DIR_CUSTOM}"
  bcm-git-volume-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${STORAGE_DIR_DATA}"
  bcm-git-volume-git:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${STORAGE_DIR_GIT}"
