name: bcm-git

networks:
  bcm-git-network:
    name: bcm-git-network
    external: false

services:

  bcm-git-server:
    container_name: bcm-git-server
    image: codeberg.org/forgejo/forgejo:15-rootless
    user: "${USER_UID}:${USER_GID}"
    restart: no
    ports:
      - "${PORT_WEB}:3000"
      - "${PORT_SSH}:2222"
    networks:
      - bcm-git-network
    depends_on:
      - bcm-git-db
    env_file:
      - .git.env
    environment:
      USER_UID: "${USER_UID}"
      USER_GID: "${USER_GID}"
      FORGEJO____APP_NAME: "${APP_NAME}"
      FORGEJO____APP_SLOGAN: "${APP_SLOGAN}"
      FORGEJO____APP_DISPLAY_NAME_FORMAT: "${APP_DISPLAY_NAME_FORMAT}"
      FORGEJO__server__ROOT_URL: "${ROOT_URL}"
      FORGEJO__ui__SHOW_USER_EMAIL: "false"
      FORGEJO__ui__THEMES: "${APP_THEME_LIST}"
      FORGEJO__ui__DEFAULT_THEME: "${APP_THEME_DEFAULT}"
      FORGEJO__database__DB_TYPE: "postgres"
      FORGEJO__database__HOST: "bcm-git-db:5432"
      FORGEJO__database__NAME: "${POSTGRES_DB}"
      FORGEJO__database__USER: "${POSTGRES_USER}"
      FORGEJO__database__PASSWD: "${POSTGRES_PASSWORD}"
    volumes:
      - "bcm-git-server-app:/var/lib/gitea"
      - "bcm-git-server-custom:/var/lib/gitea/custom"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  bcm-git-db:
    container_name: bcm-git-db
    image: postgres:14
    restart: no
    environment:
      POSTGRES_USER: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_PASSWORD}"
    networks:
      - bcm-git-network
    volumes:
      - "bcm-git-db-data:/var/lib/postgresql/data"

volumes:
  bcm-git-server-app:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${STORAGE_DIR_APP}"
  bcm-git-server-custom:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${STORAGE_DIR_CUSTOM}"
  bcm-git-db-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${STORAGE_DIR_DATABASE}"
