steps:
  - label: "Test"
    key: "test"
    env:
      DOCKER_HOST: tcp://localhost:2375
    image: alpine/docker-with-buildx:latest
    command: |
      ./src/docker/docker-build.sh
      DENO_TASK_NAME=test ./src/docker/docker-start.sh