steps:
  - label: "Test"
    key: "test"
    plugins:
      - docker:
          image: "denoland/deno:latest"
          propagate-environment: true
    command: |
      ./src/docker/docker-build.sh
      DENO_TASK_NAME=test ./src/docker/docker-start.sh