; For config options refer to https://github.com/gogs/gogs/blob/main/conf/app.ini

[server]
; The landing page URL for anonymous users, the value should not include
; subpath that is handled by the reverse proxy.
LANDING_URL = /

[repository]
DEFAULT_BRANCH = main

[ui]
; Number of repositories that are showed in one explore page
EXPLORE_PAGING_NUM = 25
; Number of issues that are showed in one page
ISSUE_PAGING_NUM = 25
; Number of maximum commits showed in one activity feed
FEED_MAX_COMMIT_NUM = 10

[ui.user]
; Number of repos that are showed in one page
REPO_PAGING_NUM = 15
; Number of news feeds that are showed in one page
NEWS_FEED_PAGING_NUM = 20
; Number of commits that are showed in one page
COMMITS_PAGING_NUM = 30
