#!/usr/bin/env bash
#MISE description="Build the Docker image"
#MISE alias="docker-build"

if [ -f ".site.env" ]; then
  mise run msg-warn 'Loading vars from env file.'
  source ".site.env"
else
  mise run msg-warn 'Loading vars from session.'
fi

mise run msg-info "Building 'bcm-site-local' Docker Image"

docker buildx build \
  --pull \
  --no-cache \
  --progress=plain \
  --platform linux/amd64 \
  --tag "bcm-site-local:latest" \
  --tag "bcm-site-local:commit-$(git rev-parse --short HEAD)" \
  --build-arg SITE_FEED_TITLE="$SITE_FEED_TITLE" \
  --build-arg SITE_FEED_DESC="$SITE_FEED_DESC" \
  --build-arg SITE_FEED_DEFAULT_TITLE="$SITE_FEED_DEFAULT_TITLE" \
  --build-arg SITE_LANG="$SITE_LANG" \
  --build-arg SITE_AUTHOR="$SITE_AUTHOR" \
  --build-arg SITE_URL="$SITE_URL" \
  --build-arg SITE_PORT="$SITE_PORT" \
  --build-arg SITE_POSTHOG_ID="$SITE_POSTHOG_ID" \
  --build-arg SITE_POSTHOG_API_HOST="$SITE_POSTHOG_API_HOST" \
  --build-arg SITE_POSTHOG_UI_HOST="$SITE_POSTHOG_UI_HOST" \
  "."
