#!/usr/bin/env bash
#MISE description="Stop the Docker container"
#MISE alias="docker-stop"

if [ "$(docker ps -aq -f name=bcm-site-local)" ]; then
  mise run msg-warn "Stopping and removing current 'bcm-site-local' container"

  docker stop "bcm-site-local" >/dev/null 2>&1
  docker rm "bcm-site-local" >/dev/null 2>&1
fi
