; For config options refer to https://github.com/gogs/gogs/blob/main/conf/app.ini

BRAND_NAME = ${BRAND_NAME}

RUN_MODE = prod
RUN_USER = git

[server]
EXTERNAL_URL     = ${APP_URL}
DOMAIN           = ${APP_DOMAIN}
START_SSH_SERVER = true
SSH_PORT         = ${SSH_PORT}
SSH_LISTEN_PORT  = ${SSH_LISTEN_PORT}

[repository]
ROOT = /data/git/gogs-repositories

[database]
TYPE     = postgres
HOST     = ${GOGS_DATABASE_HOST}
NAME     = ${GOGS_DATABASE_NAME}
USER     = ${GOGS_DATABASE_USER}
PASSWORD = ${GOGS_DATABASE_PASSWORD}

[security]
SECRET_KEY = ${GOGS_SECURITY_SECRET_KEY}

[service]
DISABLE_REGISTRATION = true

[admin]
DISABLE_REGULAR_ORG_CREATION = true

[other]
SHOW_FOOTER_TEMPLATE_LOAD_TIME = false
