#!/usr/bin/env bash
#MISE description="Start the Docker container"
#MISE alias="docker-start"
#
# Port can be customised by exporting the SITE_PORT before running the script.
# Env File Path can be customised by exporting the SITE_ENV before running the script.
#

mise run docker-stop

# Load '.env' if it exists

if [ -f ".env" ]; then
  mise run msg-info "Loading variables from '.env'"

  source ".env"

  echo "Starting 'bcm-site-local' container"
  docker run \
    -d \
    --name "bcm-site-local" \
    --env-file ".env" \
    --publish "${SITE_PORT:-8000}:8000" \
    --env "SITE_POSTHOG_ID=${SITE_POSTHOG_ID}" \
    --env "SITE_POSTHOG_API_HOST=${SITE_POSTHOG_API_HOST}" \
    --env "SITE_POSTHOG_UI_HOST=${SITE_POSTHOG_UI_HOST}" \
    "bcm-site-local:latest"
else
  mise run msg-warn "File not found at '.env'"
  mise run msg-info "Starting 'bcm-site-local' container"

  docker run \
    -d \
    --name "bcm-site-local" \
    --publish "${SITE_PORT:-8000}:8000" \
    --env "SITE_POSTHOG_ID=${SITE_POSTHOG_ID}" \
    --env "SITE_POSTHOG_API_HOST=${SITE_POSTHOG_API_HOST}" \
    --env "SITE_POSTHOG_UI_HOST=${SITE_POSTHOG_UI_HOST}" \
    "bcm-site-local:latest"
fi
