#!/usr/bin/env bash
#MISE description="Initial setup of local dev tools"
#MISE alias="setup-tools"

if command -v mise > /dev/null 2>&1 && [ -f "$HOME/.local/bin/mise" ] ; then
  mise trust
  mise run msg-info 'Activating Mise to apply config and aliases'
	eval "$($HOME/.local/bin/mise activate bash)"
fi

if command -v brew > /dev/null 2>&1; then
  mise run msg-success 'Found Homebrew'
else
  mise run msg-error 'Please install Homebrew manually - https://brew.sh/'
  exit 1
fi

if command -v docker > /dev/null 2>&1; then
  mise run msg-success 'Found Docker'
else
  mise run msg-error 'Please install Docker manually - https://www.docker.com/products/docker-desktop/'
  exit 1
fi

if command -v deno > /dev/null 2>&1; then
  mise run msg-success 'Found Deno'
else
  mise run msg-info 'Installing Deno'
  curl -fsSL https://deno.land/install.sh | sh
fi

mise run msg-info 'Installing markdownlint'
brew install markdownlint-cli > /dev/null 2>&1

mise run msg-info 'Setup env'
mise run setup-env

mise run msg-success 'Setup completed'

mise run msg-warn 'To install optional AI Code Generation tools, see https://github.com/bcm-works/dotfiles/tree/main/ai'
