#!/usr/bin/env bash
#MISE description="Build the site, run tests, then push new Docker Image to Docker Hub"
#MISE alias="release"

# Load Env Vars

if [ ! -f ".site.release.env" ]; then
  mise run msg-error "File not found at '.site.release.env'"
  exit 1
fi

source ".site.release.env"

# Configure release variables

TIMESTAMP="$(TZ='Australia/Sydney' date +%Y%m%d.%H%M)"
COMMIT="$(git rev-parse --short HEAD)"
BRANCH="$(git branch --show-current)"
SITE_DOCKER_IMAGE_URL="docker.io/$SITE_DOCKER_IMAGE_PATH"

# Prompt the user to continue or not

mise run msg-warn 'This script will push a new Docker Image to Docker Hub and trigger a Railway deployment.'
read -p "Do you want to continue? (y/N): " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  mise run msg-error 'Release cancelled'
  exit 1
fi

mise run msg-success "Release confirmed - $TIMESTAMP"

mise run msg-info 'Install dependencies'

deno ci --quiet

mise run msg-info 'Build site'

deno task build

mise run msg-info 'Build Docker Image'

deno task docker-build

mise run msg-info 'Run tests'

deno task test

mise run msg-info 'Login to Docker Hub'

echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

mise run msg-info 'Build Docker Image for Docker Hub'

docker buildx build \
  --pull \
  --no-cache \
  --progress=plain \
  --platform linux/amd64 \
  --provenance=true \
  --sbom=true \
  --attest type=provenance,mode=max \
  --tag "$SITE_DOCKER_IMAGE_URL:latest" \
  --tag "$SITE_DOCKER_IMAGE_URL:commit-$COMMIT" \
  --tag "$SITE_DOCKER_IMAGE_URL:branch-$BRANCH" \
  --tag "$SITE_DOCKER_IMAGE_URL:release-$TIMESTAMP" \
  --label "maintainer=$SITE_AUTHOR" \
  --label "org.opencontainers.image.licenses=MIT" \
  --label "org.opencontainers.image.title=$SITE_TITLE" \
  --label "org.opencontainers.image.description=$SITE_DESC" \
  --label "org.opencontainers.image.authors=$SITE_AUTHOR" \
  --label "org.opencontainers.image.vendor=$SITE_AUTHOR" \
  --label "org.opencontainers.image.url=$SITE_REPO" \
  --label "org.opencontainers.image.source=$SITE_REPO" \
  --label "org.opencontainers.image.version=$TIMESTAMP" \
  --label "org.opencontainers.image.revision=$COMMIT" \
  --build-arg SITE_FEED_TITLE="$SITE_FEED_TITLE" \
  --build-arg SITE_FEED_DESC="$SITE_FEED_DESC" \
  --build-arg SITE_FEED_DEFAULT_TITLE="$SITE_FEED_DEFAULT_TITLE" \
  --build-arg SITE_LANG="$SITE_LANG" \
  --build-arg SITE_AUTHOR="$SITE_AUTHOR" \
  --build-arg SITE_URL="$SITE_URL" \
  --build-arg SITE_PORT="$SITE_PORT" \
  --build-arg SITE_POSTHOG_ID="$SITE_POSTHOG_ID" \
  --build-arg SITE_POSTHOG_API_HOST="$SITE_POSTHOG_API_HOST" \
  --build-arg SITE_POSTHOG_UI_HOST="$SITE_POSTHOG_UI_HOST" \
  "."

mise run msg-info 'Push Docker Image to Docker Hub'

docker push "$SITE_DOCKER_IMAGE_URL:latest" > /dev/null 2>&1
docker push "$SITE_DOCKER_IMAGE_URL:commit-$COMMIT" > /dev/null 2>&1
docker push "$SITE_DOCKER_IMAGE_URL:branch-$BRANCH" > /dev/null 2>&1
docker push "$SITE_DOCKER_IMAGE_URL:release-$TIMESTAMP" > /dev/null 2>&1

mise run msg-info 'Generate release notes'

mise run release-notes "release-notes.log"

mise run msg-info 'Create and push a new Git Tag'

git tag \
  --annotate "release-$TIMESTAMP" \
  --message "release-$TIMESTAMP" \
  --message "$(cat release-notes.log)"

git push origin --tags --quiet

rm "release-notes.log"

mise run msg-success "Release complete - $TIMESTAMP"
