# Mise config - https://mise.en.dev/

[settings]
quiet = true
monorepo_root = true
experimental = false
idiomatic_version_file_enable_tools = ["npm", "node", "deno", "python"]
env_shell_expand = true
lockfile = true
minimum_release_age = "7d"

[tools]
deno = "latest"

[task]
monorepo_depth = 2
monorepo_respect_gitignore = true

[shell_alias]
tasks = "mise tasks --extended"
git-update = "mise run git:update-submodules"
git-pr = "mise run git:new-pr"
git-br = "mise run git:new-branch"
github-login = "gh auth login --web --git-protocol ssh --clipboard"
github-lint = "gh actionlint"
markdown-lint = "markdownlint --config .markdownlint.yml --fix *.md docs/ **/*.md"
release-changes = "mise run release:changes-generate"
msg = "mise run msg"
