#
#
# GitHub Actions Workflow: Release
#   - Includes the build, test, deploy, and release processes
#   - Initial setup is required, refer to README.md
#
#

name: Release
run-name: Release ${{ github.run_number }} from ${{ github.actor }} on the ${{ github.ref_name }} ${{ github.ref_type }}

on:
  # Manual run via GitHub Repo > Actions > Release > Run workflow
  workflow_dispatch:
    inputs:
      continue_deployment:
        description: 'Confirm production deployment'
        type: boolean
        required: true
        default: false

concurrency:
  group: release
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  check:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Confirmed
        if: ${{ inputs.continue_deployment != true }}
        run: echo "Not confirmed by the user" && exit 1
      - name: Branch
        if: ${{ github.ref_name != 'main' }}
        run: echo "Not on the 'main' branch" && exit 1

  build:
    name: Build and Test
    needs: [check]
    runs-on: ubuntu-latest
    environment:
      name: ci-build
      deployment: false
    env: ${{ secrets }}
    permissions:
      contents: read
    outputs:
      TIMESTAMP: ${{ steps.vars.outputs.TIMESTAMP }}
      COMMIT: ${{ steps.vars.outputs.COMMIT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          ref: 'main'
          lfs: true
          fetch-depth: 1
          show-progress: false
      - name: Set Variables
        id: vars
        run: |
          echo "TIMESTAMP=$(TZ='Australia/Sydney' date +%Y%m%d.%H%M)" >> $GITHUB_OUTPUT
          echo "COMMIT=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      - name: Deno Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Run Tests
        run: deno task test

  deploy-deno:
    name: Deno Deploy
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: ci-deploy-deno
      deployment: false
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          ref: 'main'
          lfs: true
          fetch-depth: 1
          show-progress: false
      - name: Deno Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Deploy
        run: |
          deno deploy \
            env update-value \
            SITE_BUILD_ID ${{ needs.build.outputs.TIMESTAMP }} \
            --token ${{ secrets.DENO_DEPLOY_TOKEN }} \
            --non-interactive \
            --quiet
          deno deploy \
            --token ${{ secrets.DENO_DEPLOY_TOKEN }} \
            --config deno.json \
            --prod \
            --non-interactive \
            --quiet

  release-github:
    name: Release
    needs: [build, deploy-deno]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          ref: 'main'
          lfs: true
          fetch-depth: 100
          fetch-tags: true
          show-progress: false
      - name: Deno Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Install Dependencies
        run: deno ci
      - name: Generate Release Notes
        working-directory: ${{ github.workspace }}
        run: |
          TAG_PREV=$(git tag -l "release-*" --sort=-creatordate | head -n 1)
          git log "$TAG_PREV..HEAD" \
            --oneline --no-merges \
            --format="- [%h](${{ github.server_url }}/${{ github.repository }}/commit/%H) %s" \
            > "${{ github.workspace }}/release-notes.log"
          cat ${{ github.workspace }}/release-notes.log
      - name: Create Release Tag
        run: |
          git config user.name "bot-release"
          git config user.email "brendan+bot-release@bcm.works"
          git tag release-${{ needs.build.outputs.TIMESTAMP }}
          git push --tags --quiet
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ needs.build.outputs.TIMESTAMP }}
          tag: release-${{ needs.build.outputs.TIMESTAMP }}
          bodyFile: ${{ github.workspace }}/release-notes.log
          makeLatest: true
