#
#
# GitHub Actions Workflow: Release
#   - Includes the build, test, deploy, and release processes
#   - Initial setup is required, refer to README.md
#
#

name: Release
run-name: Release by ${{ github.actor }} on ${{ github.ref_name }}

on:
  # Manual run via GitHub Repo > Actions > Release > Run workflow
  workflow_dispatch:
    inputs:
      continue_deployment:
        description: 'Confirm production deployment and release'
        type: boolean
        required: true
        default: false

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:

  release-build-test:
    name: Build and Test
    if: ${{ inputs.continue_deployment == true }}
    runs-on: ubuntu-latest
    environment:
      name: ci-build
      deployment: false
    env: ${{ secrets }}
    outputs:
      TIMESTAMP: ${{ steps.vars.outputs.TIMESTAMP }}
      COMMIT: ${{ steps.vars.outputs.COMMIT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 1
          submodules: recursive
      - name: Set workflow variables
        id: vars
        run: |
          echo "TIMESTAMP=$(TZ='Australia/Sydney' date +%Y%m%d.%H%M)" >> $GITHUB_OUTPUT
          echo "COMMIT=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      - name: Mise setup
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          chmod +x ${{ github.workspace }}/.mise/tasks/*
          chmod +x ${{ github.workspace }}/.mise/tasks/**/*
          mise trust ${{ github.workspace }}/.mise/config.toml
      - name: Deno setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Install dependencies
        run: deno ci --quiet
      - name: Build site
        run: mise run build
      - name: Docker build
        run: deno task docker-build
      - name: Run tests
        run: deno task test

  release-docker:
    name: Push to GitHub Packages
    needs: [release-build-test]
    runs-on: ubuntu-latest
    environment:
      name: ci-build
      deployment: false
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 1
          submodules: recursive
      - name: Docker Hub login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_DEPLOY_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            latest
            branch-${{ github.ref_name }}
            commit-${{ needs.release-build-test.outputs.COMMIT }}
            release-${{ needs.release-build-test.outputs.TIMESTAMP }}
          labels: |
            org.opencontainers.image.version=${{ needs.release-build-test.outputs.TIMESTAMP }}
            org.opencontainers.image.revision=${{ needs.release-build-test.outputs.COMMIT }}
      - name: Build and push Docker Image
        id: push
        uses: docker/build-push-action@v7
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          platforms: linux/amd64
          provenance: mode=max
          sbom: true
          pull: true
          push: true
          build-args: |
            SITE_URL=${{ secrets.SITE_URL }}
            SITE_PORT=${{ secrets.SITE_PORT }}
            SITE_FEED_TITLE=${{ secrets.SITE_FEED_TITLE }}
            SITE_FEED_DESC=${{ secrets.SITE_FEED_DESC }}
            SITE_FEED_DEFAULT_TITLE=${{ secrets.SITE_FEED_DEFAULT_TITLE }}
            SITE_LANG=${{ secrets.SITE_LANG }}
            SITE_AUTHOR=${{ secrets.SITE_AUTHOR }}
            SITE_POSTHOG_ID=${{ secrets.SITE_POSTHOG_ID }}
            SITE_POSTHOG_API_HOST=${{ secrets.SITE_POSTHOG_API_HOST }}
            SITE_POSTHOG_UI_HOST=${{ secrets.SITE_POSTHOG_UI_HOST }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release-github:
    name: Create Release
    needs: [release-build-test, release-docker]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Create release tag
        run: |
          git config user.name "bot-release"
          git config user.email "brendan+bot-release@bcm.works"
          git tag release-${{ needs.release-build-test.outputs.TIMESTAMP }}
          git push --tags --quiet
      - name: Install and setup Mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          chmod +x ${{ github.workspace }}/.mise/tasks/*
          chmod +x ${{ github.workspace }}/.mise/tasks/**/*
          mise trust ${{ github.workspace }}/.mise/config.toml
      - name: Generate release notes
        working-directory: ${{ github.workspace }}
        run: mise run release-notes ${{ github.workspace }}/release-notes.log
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ needs.release-build-test.outputs.TIMESTAMP }}
          tag: release-${{ needs.release-build-test.outputs.TIMESTAMP }}
          bodyFile: ${{ github.workspace }}/release-notes.log
          makeLatest: true
