#
#
# GitHub Actions Workflow: Test
#   - Includes the build and test processes
#
#

name: Test
run-name: Test by ${{ github.actor }} on ${{ github.ref_name }}

on:
  # Manual run via GitHub Repo > Actions > Test > Run workflow
  workflow_dispatch:
  # Automatically run on PRs that are targetting 'main'
  pull_request:
    branches:
      - main
    paths:
      - src/*.ts
      - src/**/*.ts
      - src/Site.Dockerfile
      - src/Site.Dockerfile.dockerignore
      - tools/
      - deno.jsonc
      - nub.lock
      - package.json

defaults:
  run:
    shell: bash

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    environment:
      name: ci-build
      deployment: false
    env: ${{ secrets }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Nub Setup
        uses: nubjs/setup-nub@v0
      - name: Deno Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Install Dependencies
        run: nub run deps-install
      - name: Build Site
        run: nub run build
      - name: Build Docker
        run: nub run docker-build
      - name: Run Tests
        run: nub run test
