#
#
# GitHub Actions Workflow: Test
#   - Includes the build and test processes
#
#

name: Test
run-name: Test from ${{ github.actor }} on the ${{ github.ref_name }} ${{ github.ref_type }}

on:
  # Manual run via GitHub Repo > Actions > Test > Run workflow
  workflow_dispatch:
  # Automatically run on PRs that are targetting 'main'
  pull_request:
    branches:
      - main
    paths:
      - src/*.ts
      - src/**/*.ts
      - src/Site.Dockerfile
      - src/Site.Dockerfile.dockerignore
      - deno.json
      - deno.lock

defaults:
  run:
    shell: bash

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    environment:
      name: ci-build
      deployment: false
    env: ${{ secrets }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Deno Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Install Dependencies
        run: deno ci
      - name: Run Checks
        run: deno task check
      - name: Build Site
        run: deno task build
      - name: Build Docker
        run: deno task docker-build
      - name: Run Tests
        run: deno task test
