#
#
# GitHub Actions Workflow: Test
#   - Includes the build and test processes
#
#

name: Test
run-name: Test by ${{ github.actor }} on ${{ github.ref_name }}

on:
  # Manual run via GitHub Repo > Actions > Test > Run workflow
  workflow_dispatch:
  # Automatically run on PRs that are targetting 'main'
  pull_request:
    branches:
      - main
    paths:
      - src/
      - tools/
      - deno.jsonc
      - nub.lock
      - package.json
      - .dockerignore
      - Dockerfile

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    environment:
      name: ci-build
      deployment: false
    env: ${{ secrets }}
    outputs:
      TIMESTAMP: ${{ steps.vars.outputs.TIMESTAMP }}
      COMMIT: ${{ steps.vars.outputs.COMMIT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set workflow variables
        id: vars
        run: |
          echo "TIMESTAMP=$(TZ='Australia/Sydney' date +%Y%m%d.%H%M)" >> $GITHUB_OUTPUT
          echo "COMMIT=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      - name: Nub setup
        uses: nubjs/setup-nub@v0
      - name: Deno setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Install dependencies
        run: nub run deps-install
      - name: Build site
        run: nub run build
      - name: Docker build
        run: nub run docker-build
      - name: Run tests
        run: deno task test
